### ISSUE TITLE
Conda env create fails

### ISSUE THREAD

**Issue by BassedWarrior** [game-devs-csf/RL-environments#18]
Cuando intenté utilizar el comando 
```
conda env create -n rl-lab-dev --file dev-environment.yml
```
del `README.md` de del repo, tuve el mensaje de error de:
```
CondaValueError: could not parse 'name: rl-lab-dev' in: dev-environment.yml
```
por lo que no se qué deba de cambiar o qué estaré haciendo mal yo, pero no me 
sirvió.

**Comment by octavio-navarro** [comment]
Probé en windows 11 y el comando que incluiste funcionó correctamente. ¿En qué OS lo estás probando?

**Comment by BassedWarrior** [comment]
Probé en Fedora Linux 39 @octavio-navarro . Maybe deba buscar en online forums

**Comment by octavio-navarro** [comment]
> Probé en Fedora Linux 39 @octavio-navarro . Maybe deba buscar en online forums

Deja levanto una máquina virtual y checo sí me deja.

**Comment by octavio-navarro** [comment]
Intenta: conda env create --file dev-environment.yml

**Comment by BassedWarrior** [comment]
Funciona sin el flag. Tal y como dijiste. Por lo que no se si sea mejor 
cambiar el `README.md` para que no lo incluya como parte del comando. Porque 
creo que es innecesario.
