### ISSUE TITLE
Exportar modelos

### ISSUE THREAD

**Issue by A01352283** [game-devs-csf/RL-environments#3]
Criterios de aceptación:

- [ ] Seleccionar formato para exportar
- [ ] Poder tomar un modelo entrenado y exportarlo de manera que se pueda almacenar y transportar a otras computadoras

**Comment by BassedWarrior** [comment]
Para exportar los modelos se van a utilizar siempre q_tables?

Porque en ese caso se puede implementar utilizando las funcionalidad
```numpy.save(file, arr)```
La cual guarda el arreglo en un archivo `.npy` que luego puede ser leido por 
```numpy.load(file)```
Y regresa un numpyarray.

**Comment by A01352283** [comment]
Sí se ve bien, nada más falta definir si se va a usar q-learning para el agente base del taller y hacer las pruebas.
