### ISSUE TITLE
Importar modelos al juego

### ISSUE THREAD

**Issue by A01352283** [game-devs-csf/RL-environments#4]
- [ ] Poder tomar uno de los modelos exportados y hacer que se puedan cargar y correr sin que genere errores

**Comment by BassedWarrior** [comment]
Igualmente que comente en el issue #3, se van a utilizar q_tables?

Porque como expuse en ese comentario, existe la funcionalidad
```
numpy.load(file)
```
que permite cargar un archivo `.npy` y generar un `ndarray` de `numpy` 
directamente. Y esta se puede cargar como una q_table sin la necesidad de 
reentrenar el modelo.

**Comment by A01352283** [comment]
Sí se ve bien, nada más falta definir si se va a usar q-learning para el agente base del taller y hacer las pruebas.
